[package]
name = "codegraph-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codegraph-core     = { path = "../codegraph-core" }
codegraph-graph    = { path = "../codegraph-graph", features = ["sqlite", "lmdb","redis","postgres","mysql", "bloom-search","fastembed"] }
codegraph-context  = { path = "../codegraph-context" }
codegraph-extract  = { path = "../codegraph-extract" }
codegraph-sboxes   = { path = "../codegraph-sboxes" }
camino = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"
camino = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
